# Generated by Django 2.1.2 on 2018-11-20 19:44

from django.db import migrations, models
import simulator.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResults',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.TextField(blank=True, help_text='A short description of the simulation')),
                ('tangle', models.TextField(blank=True, help_text='The tangle result from the simulation')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simulator.models.get_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
