# Generated by Django 2.1.2 on 2018-11-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresults',
            name='user',
            field=models.ForeignKey(editable=False, help_text='User who created the simulation', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by user'),
        ),
    ]
