# Generated by Django 2.1.2 on 2018-11-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresults',
            name='deleted',
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='time_units',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='unapproved_tips',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
