# Generated by Django 2.1.2 on 2018-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20181129_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationresults',
            old_name='tangle',
            new_name='dag',
        ),
    ]
