# Generated by Django 2.1.2 on 2018-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_simulationresults_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresults',
            name='algoithm',
            field=models.CharField(blank=True, help_text='A short description of the simulation', max_length=10),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='alpha',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='num_process',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='randomness',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='transactions',
            field=models.IntegerField(default=10),
        ),
    ]
