# Generated by Django 2.1.2 on 2018-11-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20181122_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationresults',
            old_name='algoithm',
            new_name='algorithm',
        ),
    ]
