# Generated by Django 2.2.4 on 2019-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20181210_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresults',
            name='numMalUser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='numTotalUser',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='traUser',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='alpha',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='num_process',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='randomness',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='transactions',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
