# Generated by Django 2.1.2 on 2018-11-22 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_auto_20181122_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresults',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 21, 34, 0, 472714, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='simulationresults',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
