# Generated by Django 2.1.2 on 2018-11-24 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20181122_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresults',
            name='status',
            field=models.CharField(blank=True, help_text='Status of the simulation', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 15, 32, 5, 918041, tzinfo=utc), editable=False),
        ),
    ]
