# Generated by Django 2.1.2 on 2018-11-24 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_auto_20181124_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresults',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 18, 52, 23, 402496, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simulationresults',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/result_images'),
        ),
    ]
